WeatherForecastProject/Models/DailyForecast.cs
namespace WeatherForecastProject.Models
{
    public class DailyForecast
    {
        public string DateTime { get; set; }

        public float TempMax { get; set; }

        public float TempMin { get; set; }

        public float Humidity { get; set; }

        public float PrecipProb { get; set; }

        public float Windspeed { get; set; }

        public float Cloudcover { get; set; }

        public string Sunrise { get; set; }

        public string Sunset { get; set; }
    }
}

WeatherForecastProject/Models/WeatherForecastModel.cs
namespace WeatherForecastProject.Models
{
    public class WeatherForecastModel
    {
        public string ResolvedAddress { get; set; }

        public string Timezone { get; set; }

        public DailyForecast[] Days { get; set; }
    }
}

WeatherForecastProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WeatherForecastProject.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View();
        }
    }
}

WeatherForecastProject/Controllers/WeatherForecastController.cs
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using WeatherForecastProject.Models;

namespace WeatherForecastProject.Controllers
{
    public class WeatherForecastController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WeatherForecastProject/Views/Home/Index.cshtml
@using WeatherForecastProject.Models

<h2>Welcome</h2>
<br />
<h5>Please click the button below to see the weather forecast for Port Louis, Mauritius.</h5>
<br />

<a asp-controller="WeatherForecast" asp-action="Index" class="btn btn-dark">Weather Forecast</a>

WeatherForecastProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>WeatherForecastProject</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://unpkg.com/devextreme-quill@22_2/dist/dx-quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/Site.css" />

    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
</head>

<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Weather Forecast Project</a>

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link">Welcome</a></li>
                    <li class="nav-item"><a asp-controller="WeatherForecast" asp-action="Index" class="nav-link">Weather Forecast</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container">
        @RenderBody()
    </main>
</body>

</html>

WeatherForecastProject/Views/WeatherForecast/Index.cshtml
@using WeatherForecastProject.Models

<h2>Weather Forecast</h2>

<div class="long-title">
    <h4>Port Louis, Mauritius</h4>
</div>


@(Html.DevExtreme().DataGrid<DailyForecast>()
    .ShowBorders(true)
    .DataSource(_ => _.Mvc().Controller("WeatherForecastWebAPI").LoadAction("LoadWeatherForecast").Key("DateTime"))
    .Columns(_ => {
        _.AddFor(_ => _.DateTime)
            .Caption("Date");
        _.AddFor(_ => _.TempMin)
            .Caption("Min Temp °C");
        _.AddFor(_ => _.TempMax)
            .Caption("Max Temp °C");
        _.AddFor(_ => _.Humidity)
            .Caption("Humidity %");
        _.AddFor(_ => _.PrecipProb)
            .Caption("Probability of Rain %");
        _.AddFor(_ => _.Windspeed)
            .Caption("Wind Speed km/h");
        _.AddFor(_ => _.Cloudcover)
            .Caption("Cloud Cover %");
        _.AddFor(_ => _.Sunrise);
        _.AddFor(_ => _.Sunset);
    })
    .Paging(_ => _.PageSize(10))
    .FilterRow(_ => _.Visible(true))
    .HeaderFilter(_ => _.Visible(true))

)